import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import ReduxProvider from "../store/provider";
import { Toaster } from "react-hot-toast";
import ProfileCheckProvider from "@/components/services/ProfileCheckProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProfileCheckProvider>
          <ReduxProvider>
            <Header />
            {children}
            <Toaster
              position="top-right"
              toastOptions={{
                duration: 1000,
                style: {
                  background: "#333",
                  color: "#fff",
                },
              }}
            />
          </ReduxProvider>
        </ProfileCheckProvider>
      </body>
    </html>
  );
}
