export const enquiriesData = [
  {
    id: '1',
    companyName: 'Ramakrishna IT Towerz',
    contactPerson: 'Nagaraju kapuganti',
    propertyId: 'MO-442706',
    phone: '9703903098',
    email: 'nagarajukapuganti@gmail.com',
    propertyType: 'Office for Sell',
    location: 'Kaza, Andhra Pradesh, India',
    builtupArea: '1000 Sq.ft',
    price: '65.00 Lakhs',
    avatar: '/assets/kohinoor.jpg',
    isFavorite: true,
  },
  {
    id: '2',
    companyName: 'Kohinoor By Auro Reality',
    contactPerson: 'Nagaraju',
    propertyId: 'MO-998581',
    phone: '9703903098',
    email: 'nagarajuk@marketwings.in',
    propertyType: 'Apartment for Sell',
    location: 'HITEC City, Hyderabad, Telangana 500081, India',
    builtupArea: '2195 Sq.ft',
    price: '2.74 Cr',
   avatar: '/assets/kohinoor.jpg',
    isFavorite: false,
  },
  {
    id: '3',
    companyName: 'Prestige Luxury Homes',
    contactPerson: 'Rajesh Kumar',
    propertyId: 'MO-445892',
    phone: '9876543210',
    email: 'rajesh@prestigehomes.com',
    propertyType: 'Villa for Sell',
    location: 'Jubilee Hills, Hyderabad, Telangana, India',
    builtupArea: '3500 Sq.ft',
    price: '4.25 Cr',
    avatar: '/assets/kohinoor.jpg',
    isFavorite: true,
  },
  {
    id: '4',
    companyName: 'Green Valley Constructions',
    contactPerson: 'Priya Sharma',
    propertyId: 'MO-789123',
    phone: '9988776655',
    email: 'priya@greenvalley.in',
    propertyType: 'Commercial Space for Rent',
    location: 'Gachibowli, Hyderabad, Telangana, India',
    builtupArea: '2800 Sq.ft',
    price: '85,000/month',
   avatar: '/assets/kohinoor.jpg',
    isFavorite: false,
  },
  {
    id: '5',
    companyName: 'Urban Living Developers',
    contactPerson: 'Amit Patel',
    propertyId: 'MO-556677',
    phone: '9123456789',
    email: 'amit@urbanliving.com',
    propertyType: 'Penthouse for Sell',
    location: 'Banjara Hills, Hyderabad, Telangana, India',
    builtupArea: '4200 Sq.ft',
    price: '6.50 Cr',
   avatar: '/assets/kohinoor.jpg',
    isFavorite: true,
  },
];

export const matchingTenantsData = [
  {
    id: '1',
    companyName: 'Tech Solutions Pvt Ltd',
    contactPerson: 'Suresh Reddy',
    propertyId: 'TN-001234',
    phone: '9876543210',
    email: 'suresh@techsolutions.com',
    propertyType: 'Office Space Required',
    location: 'Madhapur, Hyderabad, Telangana, India',
    builtupArea: '1500 Sq.ft',
    price: '45,000/month',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&h=100&fit=crop&crop=faces',
    isFavorite: false,
  },
  {
    id: '2',
    companyName: 'Creative Studios',
    contactPerson: 'Kavya Menon',
    propertyId: 'TN-005678',
    phone: '9765432108',
    email: 'kavya@creativestudios.in',
    propertyType: 'Studio Apartment Required',
    location: 'Film Nagar, Hyderabad, Telangana, India',
    builtupArea: '800 Sq.ft',
    price: '25,000/month',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=faces',
    isFavorite: true,
  },
];