

export const listingsData = [
  {
    id: 'MO-998581',
    title: 'Kohinoor By Auro Reality',
    price: '2.74 Cr',
    bhk: '3 BHK',
    type: 'Apartment',
    status: 'Active',
    location: 'Unfurnished East facing',
    facing: 'East facing',
    lastUpdated: '2025-02-11',
    expiry: '----',
    visibility: 'Low (Freeplan)',
    enquiries: 21,
     image: '/assets/kohinoor.jpg',
    developer: 'Auro Reality'
  },
  {
    id: 'MO-709665',
    title: 'Kohinoor By Auro Reality',
    price: '1.62 Cr',
    bhk: '2 BHK',
    type: 'Apartment',
    status: 'Active',
    location: 'Unfurnished North facing',
    facing: 'North facing',
    lastUpdated: '2025-02-11',
    expiry: '----',
    visibility: 'Low (Freeplan)',
    enquiries: 4,
   image: '/assets/kohinoor.jpg',
    developer: 'Auro Reality'
  },
  {
    id: 'MO-666175',
    title: 'Kohinoor By Auro Reality',
    price: '3.38 Cr',
    bhk: '4 BHK',
    type: 'Apartment',
    status: 'Active',
    location: 'Unfurnished North facing',
    facing: 'North facing',
    lastUpdated: '2025-02-11',
    expiry: '----',
    visibility: 'Low (Freeplan)',
    enquiries: 2,
     image: '/assets/kohinoor.jpg',
    developer: 'Auro Reality'
  },
  {
    id: 'MO-593675',
    title: 'MANGO COUNTY-2 BY KALIDINDI GROUP',
    price: '12.00 L',
    bhk: 'Plot',
    type: 'Plot',
    status: 'Active',
    location: 'South facing',
    facing: 'South facing',
    lastUpdated: '2025-01-28',
    expiry: '----',
    visibility: 'Low (Freeplan)',
    enquiries: 0,
   image: '/assets/kohinoor.jpg',
    developer: 'Kalidindi Group'
  },
  {
    id: 'MO-658799',
    title: 'Godrej Madison Avenue',
    price: '3.00 Cr',
    bhk: '3 BHK',
    type: 'Apartment',
    status: 'Active',
    location: 'Unfurnished East facing',
    facing: 'East facing',
    lastUpdated: '2025-01-28',
    expiry: '----',
    visibility: 'Low (Freeplan)',
    enquiries: 5,
    image: '/assets/kohinoor.jpg',
    developer: 'Godrej Properties'
  }
];